### ISSUE TITLE
Cannot dis-/reconnect coach

### ISSUE THREAD

**Issue by mariuslb** [jonas-ponas/expert-giggle-frontend#10]
In case of an internal error, the connected coach can still be displayed as 'successfull connected'. 
Maybe a re-connection could solve the issue. However, this isn't possible because the 'connect' button is disabled and there's no option to disconnect from the coach. 

(This happened by trying to sync data; error codes L1 & S4)

**Comment by jonas-ponas** [comment]
I added a Button to unlink the current coach connection. Then you will be able to reconnect with a fresh qrcode.
I already deployed the new frontend files. if the button doesn't show up try forcing your browser to update its cache with Ctrl-Shift-R. 
Please let me know if this fixed your problem :)

**Comment by mariuslb** [comment]
It works now🤌🏼
